spring:
  cloud:
    stream:
      bindings:
        # input:
        #   destination: orgChangeTopic
        #   content-type: application/json
        #   group: licensingGroup
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          # zkNodes: localhost # no longer needed in 2.0
          brokers: kafka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
